repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        entry: bash -c 'isort "$@"; git add -u' --
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        entry: bash -c 'black "$@"; git add -u' --
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-debugger==4.0.0",
            "flake8-mypy==17.8.0",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--django"]
      - id: check-json
      - id: requirements-txt-fixer
      - id: check-vcs-permalinks
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        exclude_types: [json]
  - repo: https://github.com/marco-c/taskcluster_yml_validator
    rev: v0.0.8
    hooks:
      - id: taskcluster_yml
  - repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
      - id: yesqa
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        exclude: ^docs/
  - repo: meta
    hooks:
      - id: check-useless-excludes
default_language_version:
  python: python3
